RegisterNuiCallback("copy_vec_3", function()
  local coords = GetEntityCoords(PlayerPedId())
  lib.setClipboard(('vec(%s, %s, %s)'):format(coords.x, coords.y, coords.z))
end)

RegisterNuiCallback("copy_vec_4", function()
  local coords = GetEntityCoords(PlayerPedId())
  local heading = GetEntityHeading(PlayerPedId())
  lib.setClipboard(('vec(%s, %s, %s, %s)'):format(coords.x, coords.y, coords.z, heading))
end)
